# Generated by Django 4.2.3 on 2024-08-03 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('categoryId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('categoryName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('CompanyId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=60)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Depertment',
            fields=[
                ('DepertmentId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=60)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applicants.company')),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('ApplicantId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('LearnerIDNumber', models.CharField(max_length=13)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=6)),
                ('EquityCode', models.CharField(max_length=12)),
                ('NationalityCode', models.CharField(default='South Africa', max_length=60)),
                ('HomeLanguage', models.CharField(max_length=15)),
                ('LearnerSurname', models.CharField(max_length=60)),
                ('LearnerFirstName', models.CharField(max_length=60)),
                ('LearnerMiddleName', models.CharField(blank=True, max_length=60, null=True)),
                ('LearnerHomeAddress1', models.CharField(max_length=100)),
                ('LearnerHomeAddress2', models.CharField(blank=True, max_length=100, null=True)),
                ('Municipality', models.CharField(max_length=50)),
                ('LearnerHomePostalCode', models.CharField(max_length=6)),
                ('STATSSAArea', models.CharField(blank=True, max_length=30, null=True)),
                ('LearnerCellPhoneNumber', models.CharField(max_length=30)),
                ('LearnerFaxNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('LearnerEmailAddress', models.CharField(blank=True, max_length=10, null=True)),
                ('Province', models.CharField(max_length=50)),
                ('Disability', models.CharField(default='no', max_length=10)),
                ('LastSchoolEMISNo', models.CharField(max_length=30)),
                ('LastSchoolName', models.CharField(max_length=100)),
                ('LastSchoolYear', models.IntegerField()),
                ('DegreeTitle', models.CharField(max_length=50, null=True)),
                ('FieldOfStudy', models.CharField(max_length=60)),
                ('NQFLevel', models.IntegerField()),
                ('RACE', models.CharField(max_length=40)),
                ('Institution', models.CharField(max_length=60)),
                ('MajorSubjects', models.TextField(default='None')),
                ('Experience', models.TextField(default='None')),
                ('isSigned', models.BooleanField(default=False)),
                ('Status', models.CharField(default='Available', max_length=60)),
                ('Depertment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applicants.depertment')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applicants.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exac',
            fields=[
                ('Management', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Position', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=60)),
                ('LastName', models.CharField(max_length=60)),
                ('Gender', models.CharField(max_length=10)),
                ('EmailAddress', models.CharField(max_length=60)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=100)),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applicants.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='depertment',
            name='Exac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applicants.exac'),
        ),
    ]
