# Generated by Django 4.2.3 on 2024-08-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='depertment',
            name='Description',
            field=models.CharField(default='None', max_length=300),
        ),
    ]
