# Generated by Django 4.2.3 on 2024-08-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_depertment_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depertment',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='DepertmentId',
            new_name='DepartmentId',
        ),
        migrations.RenameField(
            model_name='learner',
            old_name='Depertment',
            new_name='Department',
        ),
    ]
