# Generated by Django 4.2.3 on 2024-08-04 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_rename_depertment_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='Exac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applicants.exac'),
        ),
    ]
