# Generated by Django 4.2.3 on 2024-08-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0005_learner_exac'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_Recruited',
            field=models.BooleanField(default=True),
        ),
    ]
