# Generated by Django 4.2.3 on 2024-08-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0006_department_is_recruited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='LearnerEmailAddress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
