# Generated by Django 4.2.3 on 2024-08-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0007_alter_learner_learneremailaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='DOB',
            field=models.DateField(blank=True, default='N/A', null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='EquityCode',
            field=models.CharField(blank=True, default='N/A', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='LearnerCellPhoneNumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='learner',
            name='LearnerHomeAddress2',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
    ]
