# Generated by Django 4.2.3 on 2024-08-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0009_alter_learner_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='LastSchoolYear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
