# Generated by Django 4.2.3 on 2024-08-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0010_alter_learner_lastschoolyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='NQFLevel',
            field=models.CharField(max_length=5),
        ),
    ]
