# Generated by Django 5.1 on 2024-10-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0012_category_code_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='DegreeTitle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
