# Generated by Django 5.1.4 on 2025-01-21 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0013_alter_learner_degreetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dateAdded',
            field=models.DateField(default=datetime.datetime(2025, 1, 21, 9, 49, 48, 318770, tzinfo=datetime.timezone.utc)),
        ),
    ]
