# Generated by Django 5.1.4 on 2025-01-30 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0014_company_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='dateAdded',
            field=models.DateField(default=datetime.datetime(2025, 1, 30, 9, 14, 47, 852972, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='department',
            name='Description',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
