# Generated by Django 5.1.2 on 2024-11-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_query_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='name',
            field=models.CharField(default='default_name', max_length=60),
        ),
        migrations.AddField(
            model_name='query',
            name='surname',
            field=models.CharField(default='default_name', max_length=60),
        ),
    ]
