# Generated by Django 5.1.4 on 2025-01-20 13:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0013_alter_learner_degreetitle'),
        ('support', '0004_alter_query_user_anouncement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anouncement',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 20, 13, 33, 38, 875418, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='anouncement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applicants.category'),
        ),
    ]
