# Generated by Django 5.1.2 on 2024-12-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_query_resolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='resolved',
        ),
        migrations.AddField(
            model_name='query',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
