# Generated by Django 5.1.4 on 2025-01-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_alter_anouncement_date_alter_anouncement_category'),
        ('support', '0008_rename_responses_response_and_more'),
    ]

    operations = [
    ]
