# Generated by Django 5.1.4 on 2025-01-21 09:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_merge_20250121_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anouncement',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 9, 49, 48, 338903, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='response',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='support.query'),
        ),
    ]
