# Generated by Django 5.1.4 on 2025-01-30 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_alter_anouncement_date_alter_response_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anouncement',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 9, 14, 47, 873971, tzinfo=datetime.timezone.utc)),
        ),
    ]
